REGLAS = [
    {
        "numero": 1,
        "antecedentes": [
            ("edad", "adulta"),
            ("presion_sistolica", "normal"),
            ("presion_diastolica", "normal"),
            ("azucar_sangre", "normal"),
            ("temperatura_corporal", "normal"),
            ("frecuencia_cardiaca", "normal"),
        ],
        "consecuente": "bajo",
    },
    {
        "numero": 2,
        "antecedentes": [
            ("edad", "adulta"),
            ("presion_sistolica", "normal"),
            ("presion_diastolica", "normal"),
            ("azucar_sangre", "normal"),
            ("temperatura_corporal", "normal"),
            ("frecuencia_cardiaca", "elevada"),
        ],
        "consecuente": "bajo",
    },
    {
        "numero": 3,
        "antecedentes": [
            ("edad", "adulta"),
            ("presion_sistolica", "baja"),
            ("presion_diastolica", "normal"),
            ("azucar_sangre", "normal"),
            ("temperatura_corporal", "normal"),
            ("frecuencia_cardiaca", "normal"),
        ],
        "consecuente": "bajo",
    },
    {
        "numero": 4,
        "antecedentes": [
            ("edad", "adulta"),
            ("presion_sistolica", "normal"),
            ("presion_diastolica", "baja"),
            ("azucar_sangre", "normal"),
            ("temperatura_corporal", "normal"),
            ("frecuencia_cardiaca", "normal"),
        ],
        "consecuente": "bajo",
    },
    {
        "numero": 5,
        "antecedentes": [
            ("edad", "adolescente"),
            ("presion_sistolica", "normal"),
            ("presion_diastolica", "normal"),
            ("azucar_sangre", "normal"),
            ("temperatura_corporal", "normal"),
            ("frecuencia_cardiaca", "normal"),
        ],
        "consecuente": "medio",
    },
    {
        "numero": 6,
        "antecedentes": [
            ("edad", "avanzada"),
            ("presion_sistolica", "normal"),
            ("presion_diastolica", "normal"),
            ("azucar_sangre", "normal"),
            ("temperatura_corporal", "normal"),
            ("frecuencia_cardiaca", "normal"),
        ],
        "consecuente": "medio",
    },
    {
        "numero": 7,
        "antecedentes": [
            ("edad", "adolescente"),
            ("presion_sistolica", "normal"),
            ("presion_diastolica", "normal"),
            ("azucar_sangre", "normal"),
            ("temperatura_corporal", "normal"),
            ("frecuencia_cardiaca", "elevada"),
        ],
        "consecuente": "medio",
    },
    {
        "numero": 8,
        "antecedentes": [
            ("edad", "adulta"),
            ("presion_sistolica", "limitrofe"),
            ("presion_diastolica", "normal"),
            ("azucar_sangre", "normal"),
            ("temperatura_corporal", "normal"),
            ("frecuencia_cardiaca", "normal"),
        ],
        "consecuente": "medio",
    },
    {
        "numero": 9,
        "antecedentes": [
            ("edad", "adulta"),
            ("presion_sistolica", "normal"),
            ("presion_diastolica", "limitrofe"),
            ("azucar_sangre", "normal"),
            ("temperatura_corporal", "normal"),
            ("frecuencia_cardiaca", "normal"),
        ],
        "consecuente": "medio",
    },
    {
        "numero": 10,
        "antecedentes": [
            ("edad", "adulta"),
            ("presion_sistolica", "limitrofe"),
            ("presion_diastolica", "limitrofe"),
            ("azucar_sangre", "normal"),
            ("temperatura_corporal", "normal"),
            ("frecuencia_cardiaca", "normal"),
        ],
        "consecuente": "medio",
    },
    {
        "numero": 11,
        "antecedentes": [
            ("edad", "adulta"),
            ("presion_sistolica", "normal"),
            ("presion_diastolica", "normal"),
            ("azucar_sangre", "elevada"),
            ("temperatura_corporal", "normal"),
            ("frecuencia_cardiaca", "normal"),
        ],
        "consecuente": "medio",
    },
    {
        "numero": 12,
        "antecedentes": [
            ("edad", "avanzada"),
            ("presion_sistolica", "normal"),
            ("presion_diastolica", "normal"),
            ("azucar_sangre", "elevada"),
            ("temperatura_corporal", "normal"),
            ("frecuencia_cardiaca", "normal"),
        ],
        "consecuente": "medio",
    },
    {
        "numero": 13,
        "antecedentes": [
            ("edad", "adulta"),
            ("presion_sistolica", "normal"),
            ("presion_diastolica", "normal"),
            ("azucar_sangre", "normal"),
            ("temperatura_corporal", "subfebril_elevada"),
            ("frecuencia_cardiaca", "normal"),
        ],
        "consecuente": "medio",
    },
    {
        "numero": 14,
        "antecedentes": [
            ("edad", "adulta"),
            ("presion_sistolica", "normal"),
            ("presion_diastolica", "normal"),
            ("azucar_sangre", "normal"),
            ("temperatura_corporal", "normal"),
            ("frecuencia_cardiaca", "taquicardia"),
        ],
        "consecuente": "medio",
    },
    {
        "numero": 15,
        "antecedentes": [
            ("edad", "avanzada"),
            ("presion_sistolica", "limitrofe"),
            ("presion_diastolica", "normal"),
            ("azucar_sangre", "normal"),
            ("temperatura_corporal", "normal"),
            ("frecuencia_cardiaca", "normal"),
        ],
        "consecuente": "medio",
    },
    {
        "numero": 16,
        "antecedentes": [
            ("edad", "adolescente"),
            ("presion_sistolica", "limitrofe"),
            ("presion_diastolica", "limitrofe"),
            ("azucar_sangre", "normal"),
            ("temperatura_corporal", "normal"),
            ("frecuencia_cardiaca", "normal"),
        ],
        "consecuente": "medio",
    },
    {
        "numero": 17,
        "antecedentes": [
            ("edad", "adulta"),
            ("presion_sistolica", "alta"),
            ("presion_diastolica", "normal"),
            ("azucar_sangre", "normal"),
            ("temperatura_corporal", "normal"),
            ("frecuencia_cardiaca", "normal"),
        ],
        "consecuente": "alto",
    },
    {
        "numero": 18,
        "antecedentes": [
            ("edad", "adulta"),
            ("presion_sistolica", "normal"),
            ("presion_diastolica", "alta"),
            ("azucar_sangre", "normal"),
            ("temperatura_corporal", "normal"),
            ("frecuencia_cardiaca", "normal"),
        ],
        "consecuente": "alto",
    },
    {
        "numero": 19,
        "antecedentes": [
            ("edad", "adulta"),
            ("presion_sistolica", "alta"),
            ("presion_diastolica", "alta"),
            ("azucar_sangre", "normal"),
            ("temperatura_corporal", "normal"),
            ("frecuencia_cardiaca", "normal"),
        ],
        "consecuente": "alto",
    },
    {
        "numero": 20,
        "antecedentes": [
            ("edad", "adulta"),
            ("presion_sistolica", "severa"),
            ("presion_diastolica", "alta"),
            ("azucar_sangre", "normal"),
            ("temperatura_corporal", "normal"),
            ("frecuencia_cardiaca", "normal"),
        ],
        "consecuente": "alto",
    },
    {
        "numero": 21,
        "antecedentes": [
            ("edad", "adulta"),
            ("presion_sistolica", "alta"),
            ("presion_diastolica", "severa"),
            ("azucar_sangre", "normal"),
            ("temperatura_corporal", "normal"),
            ("frecuencia_cardiaca", "normal"),
        ],
        "consecuente": "alto",
    },
    {
        "numero": 22,
        "antecedentes": [
            ("edad", "adulta"),
            ("presion_sistolica", "normal"),
            ("presion_diastolica", "normal"),
            ("azucar_sangre", "muy_elevada"),
            ("temperatura_corporal", "normal"),
            ("frecuencia_cardiaca", "normal"),
        ],
        "consecuente": "alto",
    },
    {
        "numero": 23,
        "antecedentes": [
            ("edad", "avanzada"),
            ("presion_sistolica", "limitrofe"),
            ("presion_diastolica", "limitrofe"),
            ("azucar_sangre", "elevada"),
            ("temperatura_corporal", "normal"),
            ("frecuencia_cardiaca", "normal"),
        ],
        "consecuente": "alto",
    },
    {
        "numero": 24,
        "antecedentes": [
            ("edad", "adulta"),
            ("presion_sistolica", "normal"),
            ("presion_diastolica", "normal"),
            ("azucar_sangre", "normal"),
            ("temperatura_corporal", "fiebre"),
            ("frecuencia_cardiaca", "taquicardia"),
        ],
        "consecuente": "alto",
    },
    {
        "numero": 25,
        "antecedentes": [
            ("edad", "adulta"),
            ("presion_sistolica", "normal"),
            ("presion_diastolica", "normal"),
            ("azucar_sangre", "normal"),
            ("temperatura_corporal", "fiebre_alta"),
            ("frecuencia_cardiaca", "elevada"),
        ],
        "consecuente": "alto",
    },
    {
        "numero": 26,
        "antecedentes": [
            ("edad", "adulta"),
            ("presion_sistolica", "normal"),
            ("presion_diastolica", "normal"),
            ("azucar_sangre", "elevada"),
            ("temperatura_corporal", "subfebril_elevada"),
            ("frecuencia_cardiaca", "taquicardia"),
        ],
        "consecuente": "alto",
    },
    {
        "numero": 27,
        "antecedentes": [
            ("edad", "avanzada"),
            ("presion_sistolica", "alta"),
            ("presion_diastolica", "normal"),
            ("azucar_sangre", "elevada"),
            ("temperatura_corporal", "normal"),
            ("frecuencia_cardiaca", "elevada"),
        ],
        "consecuente": "alto",
    },
    {
        "numero": 28,
        "antecedentes": [
            ("edad", "avanzada"),
            ("presion_sistolica", "normal"),
            ("presion_diastolica", "alta"),
            ("azucar_sangre", "elevada"),
            ("temperatura_corporal", "normal"),
            ("frecuencia_cardiaca", "elevada"),
        ],
        "consecuente": "alto",
    },
    {
        "numero": 29,
        "antecedentes": [
            ("edad", "adolescente"),
            ("presion_sistolica", "alta"),
            ("presion_diastolica", "limitrofe"),
            ("azucar_sangre", "elevada"),
            ("temperatura_corporal", "normal"),
            ("frecuencia_cardiaca", "elevada"),
        ],
        "consecuente": "alto",
    },
    {
        "numero": 30,
        "antecedentes": [
            ("edad", "adulta"),
            ("presion_sistolica", "limitrofe"),
            ("presion_diastolica", "limitrofe"),
            ("azucar_sangre", "elevada"),
            ("temperatura_corporal", "subfebril_elevada"),
            ("frecuencia_cardiaca", "elevada"),
        ],
        "consecuente": "alto",
    },
]
