RULES = [
    {
        "id": 1,
        "antecedent": [
            ("Age", "adulta"),
            ("SystolicBP", "normal"),
            ("DiastolicBP", "normal"),
            ("BS", "normal"),
            ("BodyTemp", "normal"),
            ("HeartRate", "normal"),
        ],
        "consequent": "low",
    },
    {
        "id": 2,
        "antecedent": [
            ("Age", "adulta"),
            ("SystolicBP", "normal"),
            ("DiastolicBP", "normal"),
            ("BS", "normal"),
            ("BodyTemp", "normal"),
            ("HeartRate", "elevada"),
        ],
        "consequent": "low",
    },
    {
        "id": 3,
        "antecedent": [
            ("Age", "adulta"),
            ("SystolicBP", "baja"),
            ("DiastolicBP", "normal"),
            ("BS", "normal"),
            ("BodyTemp", "normal"),
            ("HeartRate", "normal"),
        ],
        "consequent": "low",
    },
    {
        "id": 4,
        "antecedent": [
            ("Age", "adulta"),
            ("SystolicBP", "normal"),
            ("DiastolicBP", "baja"),
            ("BS", "normal"),
            ("BodyTemp", "normal"),
            ("HeartRate", "normal"),
        ],
        "consequent": "low",
    },
    {
        "id": 5,
        "antecedent": [
            ("Age", "adolescente"),
            ("SystolicBP", "normal"),
            ("DiastolicBP", "normal"),
            ("BS", "normal"),
            ("BodyTemp", "normal"),
            ("HeartRate", "normal"),
        ],
        "consequent": "mid",
    },
    {
        "id": 6,
        "antecedent": [
            ("Age", "avanzada"),
            ("SystolicBP", "normal"),
            ("DiastolicBP", "normal"),
            ("BS", "normal"),
            ("BodyTemp", "normal"),
            ("HeartRate", "normal"),
        ],
        "consequent": "mid",
    },
    {
        "id": 7,
        "antecedent": [
            ("Age", "adolescente"),
            ("SystolicBP", "normal"),
            ("DiastolicBP", "normal"),
            ("BS", "normal"),
            ("BodyTemp", "normal"),
            ("HeartRate", "elevada"),
        ],
        "consequent": "mid",
    },
    {
        "id": 8,
        "antecedent": [
            ("Age", "adulta"),
            ("SystolicBP", "limitrofe"),
            ("DiastolicBP", "normal"),
            ("BS", "normal"),
            ("BodyTemp", "normal"),
            ("HeartRate", "normal"),
        ],
        "consequent": "mid",
    },
    {
        "id": 9,
        "antecedent": [
            ("Age", "adulta"),
            ("SystolicBP", "normal"),
            ("DiastolicBP", "limitrofe"),
            ("BS", "normal"),
            ("BodyTemp", "normal"),
            ("HeartRate", "normal"),
        ],
        "consequent": "mid",
    },
    {
        "id": 10,
        "antecedent": [
            ("Age", "adulta"),
            ("SystolicBP", "limitrofe"),
            ("DiastolicBP", "limitrofe"),
            ("BS", "normal"),
            ("BodyTemp", "normal"),
            ("HeartRate", "normal"),
        ],
        "consequent": "mid",
    },
    {
        "id": 11,
        "antecedent": [
            ("Age", "adulta"),
            ("SystolicBP", "normal"),
            ("DiastolicBP", "normal"),
            ("BS", "elevada"),
            ("BodyTemp", "normal"),
            ("HeartRate", "normal"),
        ],
        "consequent": "mid",
    },
    {
        "id": 12,
        "antecedent": [
            ("Age", "avanzada"),
            ("SystolicBP", "normal"),
            ("DiastolicBP", "normal"),
            ("BS", "elevada"),
            ("BodyTemp", "normal"),
            ("HeartRate", "normal"),
        ],
        "consequent": "mid",
    },
    {
        "id": 13,
        "antecedent": [
            ("Age", "adulta"),
            ("SystolicBP", "normal"),
            ("DiastolicBP", "normal"),
            ("BS", "normal"),
            ("BodyTemp", "subfebril_elevada"),
            ("HeartRate", "normal"),
        ],
        "consequent": "mid",
    },
    {
        "id": 14,
        "antecedent": [
            ("Age", "adulta"),
            ("SystolicBP", "normal"),
            ("DiastolicBP", "normal"),
            ("BS", "normal"),
            ("BodyTemp", "normal"),
            ("HeartRate", "taquicardia"),
        ],
        "consequent": "mid",
    },
    {
        "id": 15,
        "antecedent": [
            ("Age", "avanzada"),
            ("SystolicBP", "limitrofe"),
            ("DiastolicBP", "normal"),
            ("BS", "normal"),
            ("BodyTemp", "normal"),
            ("HeartRate", "normal"),
        ],
        "consequent": "mid",
    },
    {
        "id": 16,
        "antecedent": [
            ("Age", "adolescente"),
            ("SystolicBP", "limitrofe"),
            ("DiastolicBP", "limitrofe"),
            ("BS", "normal"),
            ("BodyTemp", "normal"),
            ("HeartRate", "normal"),
        ],
        "consequent": "mid",
    },
    {
        "id": 17,
        "antecedent": [
            ("Age", "adulta"),
            ("SystolicBP", "alta"),
            ("DiastolicBP", "normal"),
            ("BS", "normal"),
            ("BodyTemp", "normal"),
            ("HeartRate", "normal"),
        ],
        "consequent": "high",
    },
    {
        "id": 18,
        "antecedent": [
            ("Age", "adulta"),
            ("SystolicBP", "normal"),
            ("DiastolicBP", "alta"),
            ("BS", "normal"),
            ("BodyTemp", "normal"),
            ("HeartRate", "normal"),
        ],
        "consequent": "high",
    },
    {
        "id": 19,
        "antecedent": [
            ("Age", "adulta"),
            ("SystolicBP", "alta"),
            ("DiastolicBP", "alta"),
            ("BS", "normal"),
            ("BodyTemp", "normal"),
            ("HeartRate", "normal"),
        ],
        "consequent": "high",
    },
    {
        "id": 20,
        "antecedent": [
            ("Age", "adulta"),
            ("SystolicBP", "severa"),
            ("DiastolicBP", "alta"),
            ("BS", "normal"),
            ("BodyTemp", "normal"),
            ("HeartRate", "normal"),
        ],
        "consequent": "high",
    },
    {
        "id": 21,
        "antecedent": [
            ("Age", "adulta"),
            ("SystolicBP", "alta"),
            ("DiastolicBP", "severa"),
            ("BS", "normal"),
            ("BodyTemp", "normal"),
            ("HeartRate", "normal"),
        ],
        "consequent": "high",
    },
    {
        "id": 22,
        "antecedent": [
            ("Age", "adulta"),
            ("SystolicBP", "normal"),
            ("DiastolicBP", "normal"),
            ("BS", "muy_elevada"),
            ("BodyTemp", "normal"),
            ("HeartRate", "normal"),
        ],
        "consequent": "high",
    },
    {
        "id": 23,
        "antecedent": [
            ("Age", "avanzada"),
            ("SystolicBP", "limitrofe"),
            ("DiastolicBP", "limitrofe"),
            ("BS", "elevada"),
            ("BodyTemp", "normal"),
            ("HeartRate", "normal"),
        ],
        "consequent": "high",
    },
    {
        "id": 24,
        "antecedent": [
            ("Age", "adulta"),
            ("SystolicBP", "normal"),
            ("DiastolicBP", "normal"),
            ("BS", "normal"),
            ("BodyTemp", "fiebre"),
            ("HeartRate", "taquicardia"),
        ],
        "consequent": "high",
    },
    {
        "id": 25,
        "antecedent": [
            ("Age", "adulta"),
            ("SystolicBP", "normal"),
            ("DiastolicBP", "normal"),
            ("BS", "normal"),
            ("BodyTemp", "fiebre_alta"),
            ("HeartRate", "elevada"),
        ],
        "consequent": "high",
    },
    {
        "id": 26,
        "antecedent": [
            ("Age", "adulta"),
            ("SystolicBP", "normal"),
            ("DiastolicBP", "normal"),
            ("BS", "elevada"),
            ("BodyTemp", "subfebril_elevada"),
            ("HeartRate", "taquicardia"),
        ],
        "consequent": "high",
    },
    {
        "id": 27,
        "antecedent": [
            ("Age", "avanzada"),
            ("SystolicBP", "alta"),
            ("DiastolicBP", "normal"),
            ("BS", "elevada"),
            ("BodyTemp", "normal"),
            ("HeartRate", "elevada"),
        ],
        "consequent": "high",
    },
    {
        "id": 28,
        "antecedent": [
            ("Age", "avanzada"),
            ("SystolicBP", "normal"),
            ("DiastolicBP", "alta"),
            ("BS", "elevada"),
            ("BodyTemp", "normal"),
            ("HeartRate", "elevada"),
        ],
        "consequent": "high",
    },
    {
        "id": 29,
        "antecedent": [
            ("Age", "adolescente"),
            ("SystolicBP", "alta"),
            ("DiastolicBP", "limitrofe"),
            ("BS", "elevada"),
            ("BodyTemp", "normal"),
            ("HeartRate", "elevada"),
        ],
        "consequent": "high",
    },
    {
        "id": 30,
        "antecedent": [
            ("Age", "adulta"),
            ("SystolicBP", "limitrofe"),
            ("DiastolicBP", "limitrofe"),
            ("BS", "elevada"),
            ("BodyTemp", "subfebril_elevada"),
            ("HeartRate", "elevada"),
        ],
        "consequent": "high",
    },
]
